name: MySQL Test

on: [push]

jobs:
  MySQL-Test:
    runs-on: ubuntu-latest
    services:
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: dicksonone_api_test
          MYSQL_USER: dicksonone-api
          MYSQL_PASSWORD: dicksonone-api
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    container:
      image: elixir:1.13.4-alpine
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - run: apk update
      - run: apk add bash mysql-client
      - run: mysql -h mysqldb -u root < docker/provision/mysql/01-databases.sql
